### ISSUE TITLE
 When I run demo.ipynb, an error occurs.

### ISSUE THREAD

**Issue by tua123** [nilspwalter/syflow#1]
![11](https://github.com/user-attachments/assets/bd12d732-00f5-4c9b-98b3-2976e1ec6a3f)
![22](https://github.com/user-attachments/assets/84b33586-c642-4c96-bcf3-337aa011295f)

TypeError: expected TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)) (got TensorOptions(dtype=double, device=cuda:0, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))

**Comment by nilspwalter** [comment]
Hello,

it appears that your input tensor is on the GPU and your model is on the CPU. If you provide more details, I may give a more concise answer.

**Comment by tua123** [comment]
Hello, I am a programming novice. I ran demo.ipynb directly without making any changes, and then it threw an error. I'm not sure what to do next. Thank you.

**Comment by tua123** [comment]
![screenshot-20240730-111053](https://github.com/user-attachments/assets/fbf23803-6960-49c1-8667-58ac6692cb14)
Hello, I have a question, I haven't found the code for exp_utils.

**Comment by nilspwalter** [comment]
> Hello, I am a programming novice. I ran demo.ipynb directly without making any changes, and then it threw an error. I'm not sure what to do next. Thank you.

Without more information about your setup, I can not debug this. It appears that there is a problem with the memory allocation. You could try to remove lines 15 & 16 in src/methods.py. Then the code should exclusively run on CPU.

**Comment by nilspwalter** [comment]
> ![screenshot-20240730-111053](https://private-user-images.githubusercontent.com/62049711/353298927-fbf23803-6960-49c1-8667-58ac6692cb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjU4MTYsIm5iZiI6MTcyMjMyNTUxNiwicGF0aCI6Ii82MjA0OTcxMS8zNTMyOTg5MjctZmJmMjM4MDMtNjk2MC00OWMxLTg2NjctNThhYzY2OTJjYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3NDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODViYTA2MDhiOTI3N2ZmYTdhMjkzNDc2NGQ2YWZiODg3NDRlOTAyYzA3ZWI1M2MyNjA2ZTlkMWQ3OWY3MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6F2ZXC3icJSvxjdt22RoToSMDErxw1hLnOX1yW33qqI) Hello, I have a question, I haven't found the code for exp_utils.

Indeed there is a problem with the imports. Thanks for letting us know! This should be fixed now, I would kindly ask you to pull again and see if it works for you.

**Comment by tua123** [comment]
> > Hello, I am a programming novice. I ran demo.ipynb directly without making any changes, and then it threw an error. I'm not sure what to do next. Thank you.
> 
> Without more information about your setup, I can not debug this. It appears that there is a problem with the memory allocation. You could try to remove lines 15 & 16 in src/methods.py. Then the code should exclusively run on CPU.
Thank you. I've resolved this issue by updating my Python version to 3.9, and now there are no problems.

**Comment by nilspwalter** [comment]
Happy that it works now! I will close this issue then.
